### ISSUE TITLE
AccessLog.config is deprecated

### ISSUE THREAD

**Issue by davidor** [3scale/kourier#105]
There are several deprecation messages in the Gateway like this one:
```
Using deprecated option 'envoy.api.v2.listener.Filter.config' from file listener.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
```

As far as I know, what we need to do is use `v3alpha` instead of `v2` for `AccessLog` (github.com/envoyproxy/go-control-plane/envoy/config/filter/accesslog/), but that means we should switch to `v3alpha` for other modules as well, like `HttpConnectionManager`.

**Comment by jmprusi** [comment]
Closed by https://github.com/3scale/kourier/pull/120
