### ISSUE TITLE
Make knative e2e tests pass with Kourier

### ISSUE THREAD

**Issue by jmprusi** [3scale/kourier#42]
Current knative serving e2e test status: 

- [x] activator_test.go
- [x] destroypod_test.go
- [x] egress_traffic_test.go
- [x] helloworld_test.go
- [x] image_pull_error_test.go
- [x] minscale_readiness_test.go 
- [x] namespace_test.go 
- [x] pod_schedule_error_test.go 
- [x] autoscale_test.go
- [x] grpc_test.go
- [x] route_service_test.go 
- [x] service_to_service_test.go 
- [x] subroutes_test.go 
- [x] websocket_test.go

**Comment by davidor** [comment]
All passing now :smile:
