### ISSUE TITLE
Provide concise instructions for installing Knative with Kourier instead of Istio for ingress

### ISSUE THREAD

**Issue by bbrowning** [3scale/kourier#59]
The README touches on this a bit, but we should have very clear, concise, easy to follow instructions for how I can get a working Knative + Kourier install without needing to install any parts of Istio.

**Comment by jmprusi** [comment]
@bbrowning can you check the related PR(https://github.com/3scale/kourier/pull/64) and see if that is good enough? 

Thanks.

**Comment by bbrowning** [comment]
Looks great - thanks!

**Comment by davidor** [comment]
Thanks @bbrowning !
